/*
 * JS for startScreen generated by Appery.io
 */

Apperyio.getProjectGUID = function() {
    return '9e1717cf-c4fc-4029-a1c3-9d7f7b60ec03';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}

Apperyio.AppPages = [{
    "name": "TransportPopup",
    "location": "#TransportPopup"
}, {
    "name": "NewRequest",
    "location": "#NewRequest"
}, {
    "name": "Transportation",
    "location": "#Transportation"
}, {
    "name": "Success",
    "location": "#Success"
}, {
    "name": "ChildElder",
    "location": "#ChildElder"
}, {
    "name": "Sendemail",
    "location": "#Sendemail"
}, {
    "name": "Info",
    "location": "#Info"
}, {
    "name": "Groups",
    "location": "#Groups"
}, {
    "name": "startScreen",
    "location": "#startScreen"
}, {
    "name": "Profile",
    "location": "#Profile"
}];

function startScreen_js() {

    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobilebutton_2': 'startScreen_mobilebutton_2',
        'mobilelabel_6': 'startScreen_mobilelabel_6',
        'mobilegroupedbuttons_14': 'startScreen_mobilegroupedbuttons_14',
        'mobilebutton_15': 'startScreen_mobilebutton_15',
        'mobilebutton_16': 'startScreen_mobilebutton_16',
        'mobilebutton_17': 'startScreen_mobilebutton_17',
        'mobilebutton_3': 'startScreen_mobilebutton_3',
        'mobilelabel_18': 'startScreen_mobilelabel_18',
        'mobilegrid_19': 'startScreen_mobilegrid_19',
        'mobilegridcell_20': 'startScreen_mobilegridcell_20',
        'mobilelabel_29': 'startScreen_mobilelabel_29',
        'mobilegridcell_21': 'startScreen_mobilegridcell_21',
        'mobilelabel_28': 'startScreen_mobilelabel_28',
        'mobilegridcell_26': 'startScreen_mobilegridcell_26',
        'mobilelabel_30': 'startScreen_mobilelabel_30',
        'mobilegridcell_22': 'startScreen_mobilegridcell_22',
        'mobilelabel_24': 'startScreen_mobilelabel_24',
        'mobilegridcell_23': 'startScreen_mobilegridcell_23',
        'ShowDate': 'startScreen_ShowDate',
        'mobilegridcell_27': 'startScreen_mobilegridcell_27',
        'TransportLabel': 'startScreen_TransportLabel',
        'mobilenavbar_9': 'startScreen_mobilenavbar_9',
        'mobilenavbaritem_10': 'startScreen_mobilenavbaritem_10',
        'mobilenavbaritem_11': 'startScreen_mobilenavbaritem_11',
        'mobilenavbaritem_12': 'startScreen_mobilenavbaritem_12',
        'mobilenavbaritem_13': 'startScreen_mobilenavbaritem_13'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    if (navigator.userAgent.indexOf("IEMobile") != -1) {
        // Fixing issue https://github.com/jquery/jquery-mobile/issues/5424 on Windows Phone
        $("div[data-role='footer']").css("bottom", "-36px");
    }

    /*
     * Nonvisual components
     */

    Apperyio.mappings = Apperyio.mappings || {};

    Apperyio.datasources = Apperyio.datasources || {};

    Apperyio.CurrentScreen = 'startScreen';
    _.chain(Apperyio.mappings).filter(function(m) {
        return m.homeScreen === Apperyio.CurrentScreen;
    }).each(Apperyio.UIHandler.hideTemplateComponents);

    /*
     * Events and handlers
     */

    // On Load
    var startScreen_onLoad = function() {
            startScreen_elementsExtraJS();

            startScreen_deviceEvents();
            startScreen_windowEvents();
            startScreen_elementsEvents();
        };

    // screen window events


    function startScreen_windowEvents() {

        $('#startScreen').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });
        $('#startScreen').on({
            pageshow: function(event) {
                try {
                    $a.c15r("TransportLabel", "set", "text", $a.storage["TransportRequest"].get("$"))
                } catch (e) {
                    console.error(e)
                };
                try {
                    $a.c15r("ShowDate", "set", "text", $a.storage["TransportDate"].get("$"))
                } catch (e) {
                    console.error(e)
                };
            },
        });

    };

    // device events


    function startScreen_deviceEvents() {
        document.addEventListener("deviceready", function() {

        });
    };

    // screen elements extra js


    function startScreen_elementsExtraJS() {
        // screen (startScreen) extra code

    };

    // screen elements handler


    function startScreen_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });

        $(document).off("click", '#startScreen_mobileheader [name="mobilebutton_2"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('Info', {
                        transition: 'flip',
                        reverse: false
                    });

                }
            },
        }, '#startScreen_mobileheader [name="mobilebutton_2"]');

        $(document).off("click", '#startScreen_mobilecontainer [name="mobilebutton_15"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('Transportation', {
                        transition: 'slide',
                        reverse: false
                    });

                }
            },
        }, '#startScreen_mobilecontainer [name="mobilebutton_15"]');

        $(document).off("click", '#startScreen_mobilefooter [name="mobilenavbaritem_10"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('Groups', {
                        transition: 'slide',
                        reverse: false
                    });

                }
            },
        }, '#startScreen_mobilefooter [name="mobilenavbaritem_10"]');
        $(document).off("click", '#startScreen_mobilefooter [name="mobilenavbaritem_11"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('Profile', {
                        transition: 'slide',
                        reverse: false
                    });

                }
            },
        }, '#startScreen_mobilefooter [name="mobilenavbaritem_11"]');

    };

    $(document).off("pagebeforeshow", "#startScreen").on("pagebeforeshow", "#startScreen", function(event, ui) {
        Apperyio.CurrentScreen = "startScreen";
        _.chain(Apperyio.mappings).filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        }).each(Apperyio.UIHandler.hideTemplateComponents);
    });

    startScreen_onLoad();
};

$(document).off("pagecreate", "#startScreen").on("pagecreate", "#startScreen", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    startScreen_js();
});

function TransportPopup_js() {

    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobilelabel_4': 'TransportPopup_mobilelabel_4',
        'ShowInfo': 'TransportPopup_ShowInfo',
        'mobilebutton_2': 'TransportPopup_mobilebutton_2'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    if (navigator.userAgent.indexOf("IEMobile") != -1) {
        // Fixing issue https://github.com/jquery/jquery-mobile/issues/5424 on Windows Phone
        $("div[data-role='footer']").css("bottom", "-36px");
    }

    /*
     * Nonvisual components
     */

    Apperyio.mappings = Apperyio.mappings || {};

    Apperyio.datasources = Apperyio.datasources || {};

    Apperyio.CurrentScreen = 'TransportPopup';
    _.chain(Apperyio.mappings).filter(function(m) {
        return m.homeScreen === Apperyio.CurrentScreen;
    }).each(Apperyio.UIHandler.hideTemplateComponents);

    /*
     * Events and handlers
     */

    // On Load
    var TransportPopup_onLoad = function() {
            TransportPopup_elementsExtraJS();

            TransportPopup_deviceEvents();
            TransportPopup_windowEvents();
            TransportPopup_elementsEvents();
        };

    // screen window events


    function TransportPopup_windowEvents() {

        $('#TransportPopup').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });
        $('#TransportPopup').on({
            pageshow: function(event) {
                try {
                    $a.c15r("ShowInfo", "set", "text", $a.storage["TransportRequest"].get("$"))
                } catch (e) {
                    console.error(e)
                };
            },
        });

    };

    // device events


    function TransportPopup_deviceEvents() {
        document.addEventListener("deviceready", function() {

        });
    };

    // screen elements extra js


    function TransportPopup_elementsExtraJS() {
        // screen (TransportPopup) extra code

    };

    // screen elements handler


    function TransportPopup_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });

        $(document).off("click", '#TransportPopup_mobilecontainer [name="mobilebutton_2"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('startScreen', {
                        transition: 'fade',
                        reverse: false
                    });

                }
            },
        }, '#TransportPopup_mobilecontainer [name="mobilebutton_2"]');

    };

    $(document).off("pagebeforeshow", "#TransportPopup").on("pagebeforeshow", "#TransportPopup", function(event, ui) {
        Apperyio.CurrentScreen = "TransportPopup";
        _.chain(Apperyio.mappings).filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        }).each(Apperyio.UIHandler.hideTemplateComponents);
    });

    TransportPopup_onLoad();
};

$(document).off("pagecreate", "#TransportPopup").on("pagecreate", "#TransportPopup", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    TransportPopup_js();
});

function NewRequest_js() {

    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobilegrid_4': 'NewRequest_mobilegrid_4',
        'mobilegridcell_5': 'NewRequest_mobilegridcell_5',
        'mobilebutton_2': 'NewRequest_mobilebutton_2',
        'mobilegridcell_6': 'NewRequest_mobilegridcell_6',
        'mobilebutton_9': 'NewRequest_mobilebutton_9'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    if (navigator.userAgent.indexOf("IEMobile") != -1) {
        // Fixing issue https://github.com/jquery/jquery-mobile/issues/5424 on Windows Phone
        $("div[data-role='footer']").css("bottom", "-36px");
    }

    /*
     * Nonvisual components
     */

    Apperyio.mappings = Apperyio.mappings || {};

    Apperyio.datasources = Apperyio.datasources || {};

    Apperyio.CurrentScreen = 'NewRequest';
    _.chain(Apperyio.mappings).filter(function(m) {
        return m.homeScreen === Apperyio.CurrentScreen;
    }).each(Apperyio.UIHandler.hideTemplateComponents);

    /*
     * Events and handlers
     */

    // On Load
    var NewRequest_onLoad = function() {
            NewRequest_elementsExtraJS();

            NewRequest_deviceEvents();
            NewRequest_windowEvents();
            NewRequest_elementsEvents();
        };

    // screen window events


    function NewRequest_windowEvents() {

        $('#NewRequest').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });

    };

    // device events


    function NewRequest_deviceEvents() {
        document.addEventListener("deviceready", function() {

        });
    };

    // screen elements extra js


    function NewRequest_elementsExtraJS() {
        // screen (NewRequest) extra code

    };

    // screen elements handler


    function NewRequest_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });

    };

    $(document).off("pagebeforeshow", "#NewRequest").on("pagebeforeshow", "#NewRequest", function(event, ui) {
        Apperyio.CurrentScreen = "NewRequest";
        _.chain(Apperyio.mappings).filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        }).each(Apperyio.UIHandler.hideTemplateComponents);
    });

    NewRequest_onLoad();
};

$(document).off("pagecreate", "#NewRequest").on("pagecreate", "#NewRequest", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    NewRequest_js();
});

function Transportation_js() {

    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'map': 'Transportation_map',
        'marker_16': 'Transportation_marker_16',
        'mobilegrid_9': 'Transportation_mobilegrid_9',
        'mobilegridcell_10': 'Transportation_mobilegridcell_10',
        'mobilelabel_33': 'Transportation_mobilelabel_33',
        'mobilegridcell_11': 'Transportation_mobilegridcell_11',
        'mobiletextinput_19': 'Transportation_mobiletextinput_19',
        'mobilegridcell_25': 'Transportation_mobilegridcell_25',
        'mobilelabel_32': 'Transportation_mobilelabel_32',
        'mobilegridcell_26': 'Transportation_mobilegridcell_26',
        'mobiletextinput_31': 'Transportation_mobiletextinput_31',
        'mobilegridcell_27': 'Transportation_mobilegridcell_27',
        'mobilelabel_34': 'Transportation_mobilelabel_34',
        'mobilegridcell_28': 'Transportation_mobilegridcell_28',
        'DateInput': 'Transportation_DateInput',
        'mobilegridcell_29': 'Transportation_mobilegridcell_29',
        'mobilelabel_36': 'Transportation_mobilelabel_36',
        'mobilegridcell_30': 'Transportation_mobilegridcell_30',
        'mobiletextinput_37': 'Transportation_mobiletextinput_37',
        'mobilecheckboxgroup_40': 'Transportation_mobilecheckboxgroup_40',
        'mobilecheckbox_41': 'Transportation_mobilecheckbox_41',
        'mobilecheckbox_44': 'Transportation_mobilecheckbox_44',
        'mobilecheckbox_45': 'Transportation_mobilecheckbox_45',
        'TransportInfo': 'Transportation_TransportInfo',
        'ButtonSendRequest': 'Transportation_ButtonSendRequest'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    if (navigator.userAgent.indexOf("IEMobile") != -1) {
        // Fixing issue https://github.com/jquery/jquery-mobile/issues/5424 on Windows Phone
        $("div[data-role='footer']").css("bottom", "-36px");
    }

    /*
     * Nonvisual components
     */

    Apperyio.mappings = Apperyio.mappings || {};

    Apperyio.mappings["Transportation_geolocation1_onsuccess_mapping_0"] = {
        "homeScreen": "Transportation",
        "directions": [

        {
            "from_name": "geolocation1",
            "from_type": "SERVICE_RESPONSE",

            "to_name": "Transportation",
            "to_type": "UI",

            "mappings": [

            {

                "source": "$['data']['coords']['latitude']",
                "target": "$['map:latitude']"

            },

            {

                "source": "$['data']['coords']['longitude']",
                "target": "$['map:longitude']"

            },

            {

                "source": "$['data']['coords']['heading']",
                "target": "$['mobiletextinput_19:text']"

            }

            ]
        }

        ]
    };

    Apperyio.mappings["Transportation_geolocation1_onbeforesend_mapping_0"] = {
        "homeScreen": "Transportation",
        "directions": [

        {

            "to_name": "geolocation1",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "data": {
                    "options": {
                        "maximumAge": 3000,
                        "timeout": 5000,
                        "enableHighAccuracy": true,
                        "watchPosition": false
                    }
                }
            },

            "mappings": []
        }

        ]
    };

    Apperyio.mappings["Transportation_Email_onsuccess_mapping_0"] = {
        "homeScreen": "Transportation",
        "directions": []
    };

    Apperyio.mappings["Transportation_Email_onbeforesend_mapping_0"] = {
        "homeScreen": "Transportation",
        "directions": [

        {
            "from_name": "Transportation",
            "from_type": "UI",

            "to_name": "Email",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {},
                "parameters": {
                    "to": "alexander.gaber@gmail.com",
                    "subject": "WeResilient Transportation Request",
                    "from": "YourFriends@WeResilient.com",
                    "api_user": "{api_user}",
                    "api_key": "{api_key}"
                },
                "body": null
            },

            "mappings": [

            {

                "source": "$['TransportInfo:text']",
                "target": "$['parameters']['text']"

            }

            ]
        }

        ]
    };

    Apperyio.datasources = Apperyio.datasources || {};

    window.geolocation1 = Apperyio.datasources.geolocation1 = new Apperyio.DataSource(GeolocationService, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["Transportation_geolocation1_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {

            Apperyio.refreshScreenFormElements("startScreen");
        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["Transportation_geolocation1_onsuccess_mapping_0"]);
            var map = Appery('map');
            map.options['address'] = '';
            map.refresh();
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });

    window.Email = Apperyio.datasources.Email = new Apperyio.DataSource(SendGrid_MailSend, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["Transportation_Email_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {

            Apperyio.refreshScreenFormElements("startScreen");
        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["Transportation_Email_onsuccess_mapping_0"]);
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });

    Apperyio.CurrentScreen = 'Transportation';
    _.chain(Apperyio.mappings).filter(function(m) {
        return m.homeScreen === Apperyio.CurrentScreen;
    }).each(Apperyio.UIHandler.hideTemplateComponents);

    /*
     * Events and handlers
     */

    // On Load
    var Transportation_onLoad = function() {
            Transportation_elementsExtraJS();

            try {
                geolocation1.execute({});
            } catch (e) {
                console.error(e);
                hideSpinner();
            };

            Transportation_deviceEvents();
            Transportation_windowEvents();
            Transportation_elementsEvents();
        };

    // screen window events


    function Transportation_windowEvents() {

        $('#Transportation').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });

    };

    // device events


    function Transportation_deviceEvents() {
        document.addEventListener("deviceready", function() {

        });
    };

    // screen elements extra js


    function Transportation_elementsExtraJS() {
        // screen (Transportation) extra code

        /* map */

        $("[name = 'map']").wrap("<div/>");
        $("[name = 'map']").parent().css("margin-left", $("[name = 'map']").css("margin-left"));
        $("[name = 'map']").parent().css("margin-right", $("[name = 'map']").css("margin-right"));
        $("[name = 'map']").css("margin-left", '0');
        $("[name = 'map']").css("margin-right", '0');

        var map_options = {
            markerSourceName: "map_markers",
            latitude: "",
            longitude: "",
            address: "",
            zoom: 10,
            showLocationMarker: false
        }

        Apperyio.__registerComponent('map', new Apperyio.ApperyMapComponent("map", map_options));
        $("[name='map_markers'] [apperytype='marker']").attr("reRender", "map");
        $(":mobile-pagecontainer").on("pagecontainershow", function(event, ui) {
            if (Apperyio('map') != undefined) {
                Apperyio('map').refresh();
            }
        });

    };

    // screen elements handler


    function Transportation_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });

        $(document).off("click", '#Transportation_mobilecontainer [name="ButtonSendRequest"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    try {
                        Email.execute({});
                    } catch (e) {
                        console.error(e);
                        hideSpinner();
                    };
                    try {
                        $a.storage["TransportRequest"].update("$", $a.c15r($a.UIHandler.resolveGeneratedComponent('TransportInfo', this), 'get', 'text'))
                    } catch (e) {
                        console.error(e)
                    };
                    try {
                        $a.storage["TransportDate"].update("$", $a.c15r($a.UIHandler.resolveGeneratedComponent('DateInput', this), 'get', 'text'))
                    } catch (e) {
                        console.error(e)
                    };
                    Apperyio.navigateTo('TransportPopup', {
                        transition: 'pop'
                    });

                }
            },
        }, '#Transportation_mobilecontainer [name="ButtonSendRequest"]');

    };

    $(document).off("pagebeforeshow", "#Transportation").on("pagebeforeshow", "#Transportation", function(event, ui) {
        Apperyio.CurrentScreen = "Transportation";
        _.chain(Apperyio.mappings).filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        }).each(Apperyio.UIHandler.hideTemplateComponents);
    });

    Transportation_onLoad();
};

$(document).off("pagecreate", "#Transportation").on("pagecreate", "#Transportation", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    Transportation_js();
});

function Success_js() {

    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobilelabel_2': 'Success_mobilelabel_2',
        'mobilebutton_3': 'Success_mobilebutton_3'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    if (navigator.userAgent.indexOf("IEMobile") != -1) {
        // Fixing issue https://github.com/jquery/jquery-mobile/issues/5424 on Windows Phone
        $("div[data-role='footer']").css("bottom", "-36px");
    }

    /*
     * Nonvisual components
     */

    Apperyio.mappings = Apperyio.mappings || {};

    Apperyio.datasources = Apperyio.datasources || {};

    Apperyio.CurrentScreen = 'Success';
    _.chain(Apperyio.mappings).filter(function(m) {
        return m.homeScreen === Apperyio.CurrentScreen;
    }).each(Apperyio.UIHandler.hideTemplateComponents);

    /*
     * Events and handlers
     */

    // On Load
    var Success_onLoad = function() {
            Success_elementsExtraJS();

            Success_deviceEvents();
            Success_windowEvents();
            Success_elementsEvents();
        };

    // screen window events


    function Success_windowEvents() {

        $('#Success').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });

    };

    // device events


    function Success_deviceEvents() {
        document.addEventListener("deviceready", function() {

        });
    };

    // screen elements extra js


    function Success_elementsExtraJS() {
        // screen (Success) extra code

    };

    // screen elements handler


    function Success_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });

        $(document).off("click", '#Success_mobilecontainer [name="mobilebutton_3"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('startScreen', {
                        transition: 'slide',
                        reverse: true
                    });

                }
            },
        }, '#Success_mobilecontainer [name="mobilebutton_3"]');

    };

    $(document).off("pagebeforeshow", "#Success").on("pagebeforeshow", "#Success", function(event, ui) {
        Apperyio.CurrentScreen = "Success";
        _.chain(Apperyio.mappings).filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        }).each(Apperyio.UIHandler.hideTemplateComponents);
    });

    Success_onLoad();
};

$(document).off("pagecreate", "#Success").on("pagecreate", "#Success", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    Success_js();
});

function ChildElder_js() {

    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobilegrid_9': 'ChildElder_mobilegrid_9',
        'mobilegridcell_10': 'ChildElder_mobilegridcell_10',
        'mobilelabel_34': 'ChildElder_mobilelabel_34',
        'mobilegridcell_11': 'ChildElder_mobilegridcell_11',
        'DateInput': 'ChildElder_DateInput',
        'mobilegridcell_25': 'ChildElder_mobilegridcell_25',
        'mobilelabel_36': 'ChildElder_mobilelabel_36',
        'mobilegridcell_26': 'ChildElder_mobilegridcell_26',
        'mobiletextinput_37': 'ChildElder_mobiletextinput_37',
        'ChildElderInfo': 'ChildElder_ChildElderInfo',
        'ButtonSendRequest': 'ChildElder_ButtonSendRequest'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    if (navigator.userAgent.indexOf("IEMobile") != -1) {
        // Fixing issue https://github.com/jquery/jquery-mobile/issues/5424 on Windows Phone
        $("div[data-role='footer']").css("bottom", "-36px");
    }

    /*
     * Nonvisual components
     */

    Apperyio.mappings = Apperyio.mappings || {};

    Apperyio.mappings["ChildElder_geolocation1_clone_1_onbeforesend_mapping_0"] = {
        "homeScreen": "ChildElder",
        "directions": [

        {

            "to_name": "geolocation1_clone_1",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "data": {
                    "options": {
                        "maximumAge": 3000,
                        "timeout": 5000,
                        "enableHighAccuracy": true,
                        "watchPosition": false
                    }
                }
            },

            "mappings": []
        }

        ]
    };

    Apperyio.mappings["ChildElder_geolocation1_clone_1_onsuccess_mapping_0"] = {
        "homeScreen": "ChildElder",
        "directions": []
    };

    Apperyio.datasources = Apperyio.datasources || {};

    window.geolocation1_clone_1 = Apperyio.datasources.geolocation1_clone_1 = new Apperyio.DataSource(GeolocationService, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["ChildElder_geolocation1_clone_1_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {

            Apperyio.refreshScreenFormElements("startScreen");
        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["ChildElder_geolocation1_clone_1_onsuccess_mapping_0"]);
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });

    Apperyio.CurrentScreen = 'ChildElder';
    _.chain(Apperyio.mappings).filter(function(m) {
        return m.homeScreen === Apperyio.CurrentScreen;
    }).each(Apperyio.UIHandler.hideTemplateComponents);

    /*
     * Events and handlers
     */

    // On Load
    var ChildElder_onLoad = function() {
            ChildElder_elementsExtraJS();

            try {
                geolocation1_clone_1.execute({});
            } catch (e) {
                console.error(e);
                hideSpinner();
            };

            ChildElder_deviceEvents();
            ChildElder_windowEvents();
            ChildElder_elementsEvents();
        };

    // screen window events


    function ChildElder_windowEvents() {

        $('#ChildElder').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });

    };

    // device events


    function ChildElder_deviceEvents() {
        document.addEventListener("deviceready", function() {

        });
    };

    // screen elements extra js


    function ChildElder_elementsExtraJS() {
        // screen (ChildElder) extra code

    };

    // screen elements handler


    function ChildElder_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });

        $(document).off("click", '#ChildElder_mobilecontainer [name="ButtonSendRequest"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    try {
                        $a.storage["ChildRequest"].update("$", $a.c15r($a.UIHandler.resolveGeneratedComponent('mobiletextinput_37', this), 'get', 'text'))
                    } catch (e) {
                        console.error(e)
                    };
                    Apperyio.navigateTo('TransportPopup', {
                        transition: 'pop'
                    });
                    try {
                        $a.storage["TransportDate"].update("$", $a.c15r($a.UIHandler.resolveGeneratedComponent('DateInput', this), 'get', 'text'))
                    } catch (e) {
                        console.error(e)
                    };

                }
            },
        }, '#ChildElder_mobilecontainer [name="ButtonSendRequest"]');

    };

    $(document).off("pagebeforeshow", "#ChildElder").on("pagebeforeshow", "#ChildElder", function(event, ui) {
        Apperyio.CurrentScreen = "ChildElder";
        _.chain(Apperyio.mappings).filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        }).each(Apperyio.UIHandler.hideTemplateComponents);
    });

    ChildElder_onLoad();
};

$(document).off("pagecreate", "#ChildElder").on("pagecreate", "#ChildElder", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    ChildElder_js();
});

function Info_js() {

    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobilelabel_2': 'Info_mobilelabel_2'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    if (navigator.userAgent.indexOf("IEMobile") != -1) {
        // Fixing issue https://github.com/jquery/jquery-mobile/issues/5424 on Windows Phone
        $("div[data-role='footer']").css("bottom", "-36px");
    }

    /*
     * Nonvisual components
     */

    Apperyio.mappings = Apperyio.mappings || {};

    Apperyio.datasources = Apperyio.datasources || {};

    Apperyio.CurrentScreen = 'Info';
    _.chain(Apperyio.mappings).filter(function(m) {
        return m.homeScreen === Apperyio.CurrentScreen;
    }).each(Apperyio.UIHandler.hideTemplateComponents);

    /*
     * Events and handlers
     */

    // On Load
    var Info_onLoad = function() {
            Info_elementsExtraJS();

            Info_deviceEvents();
            Info_windowEvents();
            Info_elementsEvents();
        };

    // screen window events


    function Info_windowEvents() {

        $('#Info').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });

    };

    // device events


    function Info_deviceEvents() {
        document.addEventListener("deviceready", function() {

        });
    };

    // screen elements extra js


    function Info_elementsExtraJS() {
        // screen (Info) extra code

    };

    // screen elements handler


    function Info_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });

    };

    $(document).off("pagebeforeshow", "#Info").on("pagebeforeshow", "#Info", function(event, ui) {
        Apperyio.CurrentScreen = "Info";
        _.chain(Apperyio.mappings).filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        }).each(Apperyio.UIHandler.hideTemplateComponents);
    });

    Info_onLoad();
};

$(document).off("pagecreate", "#Info").on("pagecreate", "#Info", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    Info_js();
});

function Sendemail_js() {

    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'From': 'Sendemail_From',
        'To': 'Sendemail_To',
        'Subject': 'Sendemail_Subject',
        'Message': 'Sendemail_Message',
        'mobilebutton2': 'Sendemail_mobilebutton2'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    if (navigator.userAgent.indexOf("IEMobile") != -1) {
        // Fixing issue https://github.com/jquery/jquery-mobile/issues/5424 on Windows Phone
        $("div[data-role='footer']").css("bottom", "-36px");
    }

    /*
     * Nonvisual components
     */

    Apperyio.mappings = Apperyio.mappings || {};

    Apperyio.mappings["Sendemail_sendgrid_mailsend_onbeforesend_mapping_0"] = {
        "homeScreen": "Sendemail",
        "directions": [

        {
            "from_name": "Sendemail",
            "from_type": "UI",

            "to_name": "sendgrid_mailsend",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {},
                "parameters": {
                    "to": "alexander.gaber@gmail.com",
                    "subject": "WeResilient Transportation Request",
                    "from": "YourFriends@WeResilient.com",
                    "api_user": "{api_user}",
                    "api_key": "{api_key}"
                },
                "body": null
            },

            "mappings": [

            {

                "source": "$['From:text']",
                "target": "$['parameters']['from']"

            },

            {

                "source": "$['To:text']",
                "target": "$['parameters']['to']"

            },

            {

                "source": "$['Subject:text']",
                "target": "$['parameters']['subject']"

            },

            {

                "source": "$['Message:text']",
                "target": "$['parameters']['text']"

            }

            ]
        }

        ]
    };

    Apperyio.mappings["Sendemail_sendgrid_mailsend_onsuccess_mapping_0"] = {
        "homeScreen": "Sendemail",
        "directions": []
    };

    Apperyio.datasources = Apperyio.datasources || {};

    window.sendgrid_mailsend = Apperyio.datasources.sendgrid_mailsend = new Apperyio.DataSource(SendGrid_MailSend, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["Sendemail_sendgrid_mailsend_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {
            var response = JSON.parse(jqXHR.responseText);

            if (response.message == 'success') {
                alert('Email sent.');
            } else if (response.message == 'error') {
                var error = response.errors[0];
                alert('Error sending email.\n' + error + '.');
            };

            Apperyio.refreshScreenFormElements("startScreen");
        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["Sendemail_sendgrid_mailsend_onsuccess_mapping_0"]);
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });

    Apperyio.CurrentScreen = 'Sendemail';
    _.chain(Apperyio.mappings).filter(function(m) {
        return m.homeScreen === Apperyio.CurrentScreen;
    }).each(Apperyio.UIHandler.hideTemplateComponents);

    /*
     * Events and handlers
     */

    // On Load
    var Sendemail_onLoad = function() {
            Sendemail_elementsExtraJS();

            Sendemail_deviceEvents();
            Sendemail_windowEvents();
            Sendemail_elementsEvents();
        };

    // screen window events


    function Sendemail_windowEvents() {

        $('#Sendemail').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });

    };

    // device events


    function Sendemail_deviceEvents() {
        document.addEventListener("deviceready", function() {

        });
    };

    // screen elements extra js


    function Sendemail_elementsExtraJS() {
        // screen (Sendemail) extra code

    };

    // screen elements handler


    function Sendemail_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });

        $(document).off("click", '#Sendemail_mobilecontainer1 [name="mobilebutton2"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    try {
                        sendgrid_mailsend.execute({});
                    } catch (e) {
                        console.error(e);
                        hideSpinner();
                    };

                }
            },
        }, '#Sendemail_mobilecontainer1 [name="mobilebutton2"]');

    };

    $(document).off("pagebeforeshow", "#Sendemail").on("pagebeforeshow", "#Sendemail", function(event, ui) {
        Apperyio.CurrentScreen = "Sendemail";
        _.chain(Apperyio.mappings).filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        }).each(Apperyio.UIHandler.hideTemplateComponents);
    });

    Sendemail_onLoad();
};

$(document).off("pagecreate", "#Sendemail").on("pagecreate", "#Sendemail", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    Sendemail_js();
});

function Groups_js() {

    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobilelabel_3': 'Groups_mobilelabel_3',
        'mobilegrid_37': 'Groups_mobilegrid_37',
        'mobilegridcell_38': 'Groups_mobilegridcell_38',
        'mobilebutton_23': 'Groups_mobilebutton_23',
        'mobilegridcell_39': 'Groups_mobilegridcell_39',
        'mobilelabel_24': 'Groups_mobilelabel_24',
        'mobileimage_36': 'Groups_mobileimage_36',
        'mobilelabel_42': 'Groups_mobilelabel_42',
        'Supporters_45': 'Groups_Supporters_45',
        'Supporters_45_mobilegrid_25': 'Groups_Supporters_45_mobilegrid_25',
        'Supporters_45_mobilegridcell_26': 'Groups_Supporters_45_mobilegridcell_26',
        'Supporters_45_mobilebutton_9': 'Groups_Supporters_45_mobilebutton_9',
        'Supporters_45_mobilegridcell_27': 'Groups_Supporters_45_mobilegridcell_27',
        'Supporters_45_mobilebutton_10': 'Groups_Supporters_45_mobilebutton_10',
        'Supporters_45_mobilegridcell_30': 'Groups_Supporters_45_mobilegridcell_30',
        'Supporters_45_mobilebutton_17': 'Groups_Supporters_45_mobilebutton_17',
        'Supporters_45_mobilegridcell_31': 'Groups_Supporters_45_mobilegridcell_31',
        'Supporters_45_mobilebutton_18': 'Groups_Supporters_45_mobilebutton_18',
        'Supporters_45_mobilegridcell_28': 'Groups_Supporters_45_mobilegridcell_28',
        'Supporters_45_mobilelabel_19': 'Groups_Supporters_45_mobilelabel_19',
        'Supporters_45_mobilegridcell_29': 'Groups_Supporters_45_mobilegridcell_29',
        'Supporters_45_mobilelabel_20': 'Groups_Supporters_45_mobilelabel_20',
        'Supporters_45_mobilegridcell_32': 'Groups_Supporters_45_mobilegridcell_32',
        'Supporters_45_mobilelabel_21': 'Groups_Supporters_45_mobilelabel_21',
        'Supporters_45_mobilegridcell_33': 'Groups_Supporters_45_mobilegridcell_33',
        'Supporters_45_mobilelabel_22': 'Groups_Supporters_45_mobilelabel_22',
        'mobileimage_43': 'Groups_mobileimage_43',
        'mobilelabel_44': 'Groups_mobilelabel_44',
        'Supporters_46': 'Groups_Supporters_46',
        'Supporters_46_mobilegrid_25': 'Groups_Supporters_46_mobilegrid_25',
        'Supporters_46_mobilegridcell_26': 'Groups_Supporters_46_mobilegridcell_26',
        'Supporters_46_mobilebutton_9': 'Groups_Supporters_46_mobilebutton_9',
        'Supporters_46_mobilegridcell_27': 'Groups_Supporters_46_mobilegridcell_27',
        'Supporters_46_mobilebutton_10': 'Groups_Supporters_46_mobilebutton_10',
        'Supporters_46_mobilegridcell_30': 'Groups_Supporters_46_mobilegridcell_30',
        'Supporters_46_mobilebutton_17': 'Groups_Supporters_46_mobilebutton_17',
        'Supporters_46_mobilegridcell_31': 'Groups_Supporters_46_mobilegridcell_31',
        'Supporters_46_mobilebutton_18': 'Groups_Supporters_46_mobilebutton_18',
        'Supporters_46_mobilegridcell_28': 'Groups_Supporters_46_mobilegridcell_28',
        'Supporters_46_mobilelabel_19': 'Groups_Supporters_46_mobilelabel_19',
        'Supporters_46_mobilegridcell_29': 'Groups_Supporters_46_mobilegridcell_29',
        'Supporters_46_mobilelabel_20': 'Groups_Supporters_46_mobilelabel_20',
        'Supporters_46_mobilegridcell_32': 'Groups_Supporters_46_mobilegridcell_32',
        'Supporters_46_mobilelabel_21': 'Groups_Supporters_46_mobilelabel_21',
        'Supporters_46_mobilegridcell_33': 'Groups_Supporters_46_mobilegridcell_33',
        'Supporters_46_mobilelabel_22': 'Groups_Supporters_46_mobilelabel_22',
        'mobilebutton_47': 'Groups_mobilebutton_47'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    if (navigator.userAgent.indexOf("IEMobile") != -1) {
        // Fixing issue https://github.com/jquery/jquery-mobile/issues/5424 on Windows Phone
        $("div[data-role='footer']").css("bottom", "-36px");
    }

    /*
     * Nonvisual components
     */

    Apperyio.mappings = Apperyio.mappings || {};

    Apperyio.mappings["Groups_contacts1_onsuccess_mapping_0"] = {
        "homeScreen": "Groups",
        "directions": []
    };

    Apperyio.mappings["Groups_contacts1_onbeforesend_mapping_0"] = {
        "homeScreen": "Groups",
        "directions": [

        {

            "to_name": "contacts1",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "data": {
                    "options": {
                        "multiple": true
                    },
                    "params": {
                        "fields": "*"
                    }
                }
            },

            "mappings": []
        }

        ]
    };

    Apperyio.datasources = Apperyio.datasources || {};

    window.contacts1 = Apperyio.datasources.contacts1 = new Apperyio.DataSource(ContactsService, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["Groups_contacts1_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {

            Apperyio.refreshScreenFormElements("startScreen");
        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["Groups_contacts1_onsuccess_mapping_0"]);
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });

    Apperyio.CurrentScreen = 'Groups';
    _.chain(Apperyio.mappings).filter(function(m) {
        return m.homeScreen === Apperyio.CurrentScreen;
    }).each(Apperyio.UIHandler.hideTemplateComponents);

    /*
     * Events and handlers
     */

    // On Load
    var Groups_onLoad = function() {
            Groups_elementsExtraJS();

            Groups_deviceEvents();
            Groups_windowEvents();
            Groups_elementsEvents();
        };

    // screen window events


    function Groups_windowEvents() {

        $('#Groups').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });

    };

    // device events


    function Groups_deviceEvents() {
        document.addEventListener("deviceready", function() {

        });
    };

    // screen elements extra js


    function Groups_elementsExtraJS() {
        // screen (Groups) extra code

    };

    // screen elements handler


    function Groups_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });

        $(document).off("click", '#Groups_mobilecontainer [name="mobilebutton_23"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    try {
                        contacts1.execute({});
                    } catch (e) {
                        console.error(e);
                        hideSpinner();
                    };

                }
            },
        }, '#Groups_mobilecontainer [name="mobilebutton_23"]');

    };

    $(document).off("pagebeforeshow", "#Groups").on("pagebeforeshow", "#Groups", function(event, ui) {
        Apperyio.CurrentScreen = "Groups";
        _.chain(Apperyio.mappings).filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        }).each(Apperyio.UIHandler.hideTemplateComponents);
    });

    Groups_onLoad();
};

$(document).off("pagecreate", "#Groups").on("pagecreate", "#Groups", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    Groups_js();
});

function Profile_js() {

    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobilegrid_3': 'Profile_mobilegrid_3',
        'mobilegridcell_4': 'Profile_mobilegridcell_4',
        'mobileimage_2': 'Profile_mobileimage_2',
        'mobilegridcell_5': 'Profile_mobilegridcell_5',
        'mobilebutton_8': 'Profile_mobilebutton_8',
        'mobilelabel_9': 'Profile_mobilelabel_9',
        'AboutMeText': 'Profile_AboutMeText',
        'mobilebutton_12': 'Profile_mobilebutton_12'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    if (navigator.userAgent.indexOf("IEMobile") != -1) {
        // Fixing issue https://github.com/jquery/jquery-mobile/issues/5424 on Windows Phone
        $("div[data-role='footer']").css("bottom", "-36px");
    }

    /*
     * Nonvisual components
     */

    Apperyio.mappings = Apperyio.mappings || {};

    Apperyio.mappings["Profile_mobilecamera1_onsuccess_mapping_0"] = {
        "homeScreen": "Profile",
        "directions": [

        {
            "from_name": "mobilecamera1",
            "from_type": "SERVICE_RESPONSE",

            "to_name": "Profile",
            "to_type": "UI",

            "mappings": [

            {

                "source": "$['data']['imageDataBase64']",
                "target": "$['mobileimage_2:image']"

            }

            ]
        }

        ]
    };

    Apperyio.mappings["Profile_mobilecamera1_onbeforesend_mapping_0"] = {
        "homeScreen": "Profile",
        "directions": [

        {

            "to_name": "mobilecamera1",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "data": {
                    "quality": 80,
                    "destinationType": "Data URL",
                    "sourceType": "Camera",
                    "allowEdit": true,
                    "encodingType": "JPEG",
                    "targetWidth": 1024,
                    "targetHeight": 768
                }
            },

            "mappings": []
        }

        ]
    };

    Apperyio.datasources = Apperyio.datasources || {};

    window.mobilecamera1 = Apperyio.datasources.mobilecamera1 = new Apperyio.DataSource(CameraService, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["Profile_mobilecamera1_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {

            Apperyio.refreshScreenFormElements("startScreen");
        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["Profile_mobilecamera1_onsuccess_mapping_0"]);
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });

    Apperyio.CurrentScreen = 'Profile';
    _.chain(Apperyio.mappings).filter(function(m) {
        return m.homeScreen === Apperyio.CurrentScreen;
    }).each(Apperyio.UIHandler.hideTemplateComponents);

    /*
     * Events and handlers
     */

    // On Load
    var Profile_onLoad = function() {
            Profile_elementsExtraJS();

            Profile_deviceEvents();
            Profile_windowEvents();
            Profile_elementsEvents();
        };

    // screen window events


    function Profile_windowEvents() {

        $('#Profile').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });
        $('#Profile').on({
            pageshow: function(event) {
                try {
                    $a.c15r("AboutMeText", "set", "text", $a.storage["AboutMe"].get("$"))
                } catch (e) {
                    console.error(e)
                };
            },
        });

    };

    // device events


    function Profile_deviceEvents() {
        document.addEventListener("deviceready", function() {

        });
    };

    // screen elements extra js


    function Profile_elementsExtraJS() {
        // screen (Profile) extra code

    };

    // screen elements handler


    function Profile_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });

        $(document).off("click", '#Profile_mobilecontainer [name="mobilebutton_8"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    try {
                        mobilecamera1.execute({});
                    } catch (e) {
                        console.error(e);
                        hideSpinner();
                    };

                }
            },
        }, '#Profile_mobilecontainer [name="mobilebutton_8"]');

        $(document).off("click", '#Profile_mobilecontainer [name="mobilebutton_12"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    try {
                        $a.storage["AboutMe"].update("$", $a.c15r($a.UIHandler.resolveGeneratedComponent('AboutMeText', this), 'get', 'text'))
                    } catch (e) {
                        console.error(e)
                    };
                    Apperyio.navigateTo('Success', {
                        transition: 'pop'
                    });

                }
            },
        }, '#Profile_mobilecontainer [name="mobilebutton_12"]');

    };

    $(document).off("pagebeforeshow", "#Profile").on("pagebeforeshow", "#Profile", function(event, ui) {
        Apperyio.CurrentScreen = "Profile";
        _.chain(Apperyio.mappings).filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        }).each(Apperyio.UIHandler.hideTemplateComponents);
    });

    Profile_onLoad();
};

$(document).off("pagecreate", "#Profile").on("pagecreate", "#Profile", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    Profile_js();
});